/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ogon_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




return_ec::~return_ec() noexcept {
}


void return_ec::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_ec::__set_cardContext(const SCARDCONTEXT_RPC val) {
  this->cardContext = val;
}
std::ostream& operator<<(std::ostream& out, const return_ec& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_ec::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->cardContext);
          this->__isset.cardContext = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_ec::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_ec");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("cardContext", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->cardContext);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_ec &a, return_ec &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.cardContext, b.cardContext);
  swap(a.__isset, b.__isset);
}

return_ec::return_ec(const return_ec& other0) {
  retValue = other0.retValue;
  cardContext = other0.cardContext;
  __isset = other0.__isset;
}
return_ec& return_ec::operator=(const return_ec& other1) {
  retValue = other1.retValue;
  cardContext = other1.cardContext;
  __isset = other1.__isset;
  return *this;
}
void return_ec::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_ec(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "cardContext=" << to_string(cardContext);
  out << ")";
}


return_rc::~return_rc() noexcept {
}


void return_rc::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}
std::ostream& operator<<(std::ostream& out, const return_rc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_rc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_rc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_rc");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_rc &a, return_rc &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.__isset, b.__isset);
}

return_rc::return_rc(const return_rc& other2) {
  retValue = other2.retValue;
  __isset = other2.__isset;
}
return_rc& return_rc::operator=(const return_rc& other3) {
  retValue = other3.retValue;
  __isset = other3.__isset;
  return *this;
}
void return_rc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_rc(";
  out << "retValue=" << to_string(retValue);
  out << ")";
}


return_lr::~return_lr() noexcept {
}


void return_lr::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_lr::__set_mszReaders(const LPSTR_RPC& val) {
  this->mszReaders = val;
}

void return_lr::__set_pcchReaders(const DWORD_RPC val) {
  this->pcchReaders = val;
}
std::ostream& operator<<(std::ostream& out, const return_lr& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_lr::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->mszReaders);
          this->__isset.mszReaders = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pcchReaders);
          this->__isset.pcchReaders = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_lr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_lr");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("mszReaders", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->mszReaders);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pcchReaders", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->pcchReaders);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_lr &a, return_lr &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.mszReaders, b.mszReaders);
  swap(a.pcchReaders, b.pcchReaders);
  swap(a.__isset, b.__isset);
}

return_lr::return_lr(const return_lr& other4) {
  retValue = other4.retValue;
  mszReaders = other4.mszReaders;
  pcchReaders = other4.pcchReaders;
  __isset = other4.__isset;
}
return_lr& return_lr::operator=(const return_lr& other5) {
  retValue = other5.retValue;
  mszReaders = other5.mszReaders;
  pcchReaders = other5.pcchReaders;
  __isset = other5.__isset;
  return *this;
}
void return_lr::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_lr(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "mszReaders=" << to_string(mszReaders);
  out << ", " << "pcchReaders=" << to_string(pcchReaders);
  out << ")";
}


return_c::~return_c() noexcept {
}


void return_c::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_c::__set_phCard(const SCARDHANDLE_RPC val) {
  this->phCard = val;
}

void return_c::__set_pdwActiveProtocol(const DWORD_RPC val) {
  this->pdwActiveProtocol = val;
}
std::ostream& operator<<(std::ostream& out, const return_c& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_c::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->phCard);
          this->__isset.phCard = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pdwActiveProtocol);
          this->__isset.pdwActiveProtocol = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_c::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_c");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("phCard", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->phCard);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pdwActiveProtocol", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->pdwActiveProtocol);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_c &a, return_c &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.phCard, b.phCard);
  swap(a.pdwActiveProtocol, b.pdwActiveProtocol);
  swap(a.__isset, b.__isset);
}

return_c::return_c(const return_c& other6) {
  retValue = other6.retValue;
  phCard = other6.phCard;
  pdwActiveProtocol = other6.pdwActiveProtocol;
  __isset = other6.__isset;
}
return_c& return_c::operator=(const return_c& other7) {
  retValue = other7.retValue;
  phCard = other7.phCard;
  pdwActiveProtocol = other7.pdwActiveProtocol;
  __isset = other7.__isset;
  return *this;
}
void return_c::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_c(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "phCard=" << to_string(phCard);
  out << ", " << "pdwActiveProtocol=" << to_string(pdwActiveProtocol);
  out << ")";
}


return_s::~return_s() noexcept {
}


void return_s::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_s::__set_szReaderName(const LPSTR_RPC& val) {
  this->szReaderName = val;
}

void return_s::__set_pcchReaderLen(const DWORD_RPC val) {
  this->pcchReaderLen = val;
}

void return_s::__set_pdwState(const DWORD_RPC val) {
  this->pdwState = val;
}

void return_s::__set_pdwProtocol(const DWORD_RPC val) {
  this->pdwProtocol = val;
}

void return_s::__set_pbAtr(const LPBYTE_RPC& val) {
  this->pbAtr = val;
}
std::ostream& operator<<(std::ostream& out, const return_s& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_s::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->szReaderName);
          this->__isset.szReaderName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pcchReaderLen);
          this->__isset.pcchReaderLen = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pdwState);
          this->__isset.pdwState = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pdwProtocol);
          this->__isset.pdwProtocol = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->pbAtr);
          this->__isset.pbAtr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_s::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_s");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("szReaderName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->szReaderName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pcchReaderLen", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->pcchReaderLen);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pdwState", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->pdwState);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pdwProtocol", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->pdwProtocol);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pbAtr", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeBinary(this->pbAtr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_s &a, return_s &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.szReaderName, b.szReaderName);
  swap(a.pcchReaderLen, b.pcchReaderLen);
  swap(a.pdwState, b.pdwState);
  swap(a.pdwProtocol, b.pdwProtocol);
  swap(a.pbAtr, b.pbAtr);
  swap(a.__isset, b.__isset);
}

return_s::return_s(const return_s& other8) {
  retValue = other8.retValue;
  szReaderName = other8.szReaderName;
  pcchReaderLen = other8.pcchReaderLen;
  pdwState = other8.pdwState;
  pdwProtocol = other8.pdwProtocol;
  pbAtr = other8.pbAtr;
  __isset = other8.__isset;
}
return_s& return_s::operator=(const return_s& other9) {
  retValue = other9.retValue;
  szReaderName = other9.szReaderName;
  pcchReaderLen = other9.pcchReaderLen;
  pdwState = other9.pdwState;
  pdwProtocol = other9.pdwProtocol;
  pbAtr = other9.pbAtr;
  __isset = other9.__isset;
  return *this;
}
void return_s::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_s(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "szReaderName=" << to_string(szReaderName);
  out << ", " << "pcchReaderLen=" << to_string(pcchReaderLen);
  out << ", " << "pdwState=" << to_string(pdwState);
  out << ", " << "pdwProtocol=" << to_string(pdwProtocol);
  out << ", " << "pbAtr=" << to_string(pbAtr);
  out << ")";
}


scard_io_request_rpc::~scard_io_request_rpc() noexcept {
}


void scard_io_request_rpc::__set_dwProtocol(const LONG_RPC val) {
  this->dwProtocol = val;
}

void scard_io_request_rpc::__set_cbPciLength(const LONG_RPC val) {
  this->cbPciLength = val;
}
std::ostream& operator<<(std::ostream& out, const scard_io_request_rpc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t scard_io_request_rpc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->dwProtocol);
          this->__isset.dwProtocol = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->cbPciLength);
          this->__isset.cbPciLength = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t scard_io_request_rpc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("scard_io_request_rpc");

  xfer += oprot->writeFieldBegin("dwProtocol", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->dwProtocol);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("cbPciLength", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->cbPciLength);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(scard_io_request_rpc &a, scard_io_request_rpc &b) {
  using ::std::swap;
  swap(a.dwProtocol, b.dwProtocol);
  swap(a.cbPciLength, b.cbPciLength);
  swap(a.__isset, b.__isset);
}

scard_io_request_rpc::scard_io_request_rpc(const scard_io_request_rpc& other10) {
  dwProtocol = other10.dwProtocol;
  cbPciLength = other10.cbPciLength;
  __isset = other10.__isset;
}
scard_io_request_rpc& scard_io_request_rpc::operator=(const scard_io_request_rpc& other11) {
  dwProtocol = other11.dwProtocol;
  cbPciLength = other11.cbPciLength;
  __isset = other11.__isset;
  return *this;
}
void scard_io_request_rpc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "scard_io_request_rpc(";
  out << "dwProtocol=" << to_string(dwProtocol);
  out << ", " << "cbPciLength=" << to_string(cbPciLength);
  out << ")";
}


return_t::~return_t() noexcept {
}


void return_t::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_t::__set_pioRecvPci(const scard_io_request_rpc& val) {
  this->pioRecvPci = val;
}

void return_t::__set_pbRecvBuffer(const LPBYTE_RPC& val) {
  this->pbRecvBuffer = val;
}
std::ostream& operator<<(std::ostream& out, const return_t& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_t::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->pioRecvPci.read(iprot);
          this->__isset.pioRecvPci = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->pbRecvBuffer);
          this->__isset.pbRecvBuffer = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_t::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_t");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pioRecvPci", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->pioRecvPci.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pbRecvBuffer", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeBinary(this->pbRecvBuffer);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_t &a, return_t &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.pioRecvPci, b.pioRecvPci);
  swap(a.pbRecvBuffer, b.pbRecvBuffer);
  swap(a.__isset, b.__isset);
}

return_t::return_t(const return_t& other12) {
  retValue = other12.retValue;
  pioRecvPci = other12.pioRecvPci;
  pbRecvBuffer = other12.pbRecvBuffer;
  __isset = other12.__isset;
}
return_t& return_t::operator=(const return_t& other13) {
  retValue = other13.retValue;
  pioRecvPci = other13.pioRecvPci;
  pbRecvBuffer = other13.pbRecvBuffer;
  __isset = other13.__isset;
  return *this;
}
void return_t::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_t(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "pioRecvPci=" << to_string(pioRecvPci);
  out << ", " << "pbRecvBuffer=" << to_string(pbRecvBuffer);
  out << ")";
}


return_r::~return_r() noexcept {
}


void return_r::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_r::__set_pdwActiveProtocol(const DWORD_RPC val) {
  this->pdwActiveProtocol = val;
}
std::ostream& operator<<(std::ostream& out, const return_r& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_r::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->pdwActiveProtocol);
          this->__isset.pdwActiveProtocol = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_r::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_r");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pdwActiveProtocol", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->pdwActiveProtocol);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_r &a, return_r &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.pdwActiveProtocol, b.pdwActiveProtocol);
  swap(a.__isset, b.__isset);
}

return_r::return_r(const return_r& other14) {
  retValue = other14.retValue;
  pdwActiveProtocol = other14.pdwActiveProtocol;
  __isset = other14.__isset;
}
return_r& return_r::operator=(const return_r& other15) {
  retValue = other15.retValue;
  pdwActiveProtocol = other15.pdwActiveProtocol;
  __isset = other15.__isset;
  return *this;
}
void return_r::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_r(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "pdwActiveProtocol=" << to_string(pdwActiveProtocol);
  out << ")";
}


scard_readerstate_rpc::~scard_readerstate_rpc() noexcept {
}


void scard_readerstate_rpc::__set_szReader(const LPSTR_RPC& val) {
  this->szReader = val;
}

void scard_readerstate_rpc::__set_dwCurrentState(const DWORD_RPC val) {
  this->dwCurrentState = val;
}

void scard_readerstate_rpc::__set_dwEventState(const DWORD_RPC val) {
  this->dwEventState = val;
}

void scard_readerstate_rpc::__set_rgbAtr(const LPBYTE_RPC& val) {
  this->rgbAtr = val;
}
std::ostream& operator<<(std::ostream& out, const scard_readerstate_rpc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t scard_readerstate_rpc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->szReader);
          this->__isset.szReader = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->dwCurrentState);
          this->__isset.dwCurrentState = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->dwEventState);
          this->__isset.dwEventState = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->rgbAtr);
          this->__isset.rgbAtr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t scard_readerstate_rpc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("scard_readerstate_rpc");

  xfer += oprot->writeFieldBegin("szReader", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->szReader);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("dwCurrentState", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->dwCurrentState);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("dwEventState", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->dwEventState);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("rgbAtr", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeBinary(this->rgbAtr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(scard_readerstate_rpc &a, scard_readerstate_rpc &b) {
  using ::std::swap;
  swap(a.szReader, b.szReader);
  swap(a.dwCurrentState, b.dwCurrentState);
  swap(a.dwEventState, b.dwEventState);
  swap(a.rgbAtr, b.rgbAtr);
  swap(a.__isset, b.__isset);
}

scard_readerstate_rpc::scard_readerstate_rpc(const scard_readerstate_rpc& other16) {
  szReader = other16.szReader;
  dwCurrentState = other16.dwCurrentState;
  dwEventState = other16.dwEventState;
  rgbAtr = other16.rgbAtr;
  __isset = other16.__isset;
}
scard_readerstate_rpc& scard_readerstate_rpc::operator=(const scard_readerstate_rpc& other17) {
  szReader = other17.szReader;
  dwCurrentState = other17.dwCurrentState;
  dwEventState = other17.dwEventState;
  rgbAtr = other17.rgbAtr;
  __isset = other17.__isset;
  return *this;
}
void scard_readerstate_rpc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "scard_readerstate_rpc(";
  out << "szReader=" << to_string(szReader);
  out << ", " << "dwCurrentState=" << to_string(dwCurrentState);
  out << ", " << "dwEventState=" << to_string(dwEventState);
  out << ", " << "rgbAtr=" << to_string(rgbAtr);
  out << ")";
}


return_gsc::~return_gsc() noexcept {
}


void return_gsc::__set_retValue(const LONG_RPC val) {
  this->retValue = val;
}

void return_gsc::__set_rgReaderStates(const std::vector<scard_readerstate_rpc> & val) {
  this->rgReaderStates = val;
}
std::ostream& operator<<(std::ostream& out, const return_gsc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t return_gsc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->retValue);
          this->__isset.retValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->rgReaderStates.clear();
            uint32_t _size18;
            ::apache::thrift::protocol::TType _etype21;
            xfer += iprot->readListBegin(_etype21, _size18);
            this->rgReaderStates.resize(_size18);
            uint32_t _i22;
            for (_i22 = 0; _i22 < _size18; ++_i22)
            {
              xfer += this->rgReaderStates[_i22].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.rgReaderStates = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t return_gsc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("return_gsc");

  xfer += oprot->writeFieldBegin("retValue", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->retValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("rgReaderStates", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->rgReaderStates.size()));
    std::vector<scard_readerstate_rpc> ::const_iterator _iter23;
    for (_iter23 = this->rgReaderStates.begin(); _iter23 != this->rgReaderStates.end(); ++_iter23)
    {
      xfer += (*_iter23).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(return_gsc &a, return_gsc &b) {
  using ::std::swap;
  swap(a.retValue, b.retValue);
  swap(a.rgReaderStates, b.rgReaderStates);
  swap(a.__isset, b.__isset);
}

return_gsc::return_gsc(const return_gsc& other24) {
  retValue = other24.retValue;
  rgReaderStates = other24.rgReaderStates;
  __isset = other24.__isset;
}
return_gsc& return_gsc::operator=(const return_gsc& other25) {
  retValue = other25.retValue;
  rgReaderStates = other25.rgReaderStates;
  __isset = other25.__isset;
  return *this;
}
void return_gsc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "return_gsc(";
  out << "retValue=" << to_string(retValue);
  out << ", " << "rgReaderStates=" << to_string(rgReaderStates);
  out << ")";
}


