/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OGON_H
#define OGON_H

#include <thrift/c_glib/processor/thrift_dispatch_processor.h>

#include "ogon_types.h"


#ifdef __cplusplus
extern "C" {
#endif


/* ogon service interface */
typedef struct _ogonIf ogonIf;  /* dummy object */

struct _ogonIfInterface
{
  GTypeInterface parent;

  gboolean (*establish_context) (ogonIf *iface, return_ec ** _return, const DWORD_RPC dwScope, GError **error);
  gboolean (*list_readers) (ogonIf *iface, return_lr ** _return, const SCARDCONTEXT_RPC hContext, GError **error);
};
typedef struct _ogonIfInterface ogonIfInterface;

GType ogon_if_get_type (void);
#define TYPE_OGON_IF (ogon_if_get_type())
#define OGON_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_IF, ogonIf))
#define IS_OGON_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_IF))
#define OGON_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), TYPE_OGON_IF, ogonIfInterface))

gboolean ogon_if_establish_context (ogonIf *iface, return_ec ** _return, const DWORD_RPC dwScope, GError **error);
gboolean ogon_if_list_readers (ogonIf *iface, return_lr ** _return, const SCARDCONTEXT_RPC hContext, GError **error);

/* ogon service client */
struct _ogonClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _ogonClient ogonClient;

struct _ogonClientClass
{
  GObjectClass parent;
};
typedef struct _ogonClientClass ogonClientClass;

GType ogon_client_get_type (void);
#define TYPE_OGON_CLIENT (ogon_client_get_type())
#define OGON_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_CLIENT, ogonClient))
#define OGON_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_OGON_CLIENT, ogonClientClass))
#define OGON_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_CLIENT))
#define OGON_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_CLIENT))
#define OGON_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_CLIENT, ogonClientClass))

gboolean ogon_client_establish_context (ogonIf * iface, return_ec ** _return, const DWORD_RPC dwScope, GError ** error);
gboolean ogon_client_send_establish_context (ogonIf * iface, const DWORD_RPC dwScope, GError ** error);
gboolean ogon_client_recv_establish_context (ogonIf * iface, return_ec ** _return, GError ** error);
gboolean ogon_client_list_readers (ogonIf * iface, return_lr ** _return, const SCARDCONTEXT_RPC hContext, GError ** error);
gboolean ogon_client_send_list_readers (ogonIf * iface, const SCARDCONTEXT_RPC hContext, GError ** error);
gboolean ogon_client_recv_list_readers (ogonIf * iface, return_lr ** _return, GError ** error);
void ogon_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void ogon_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

/* ogon handler (abstract base class) */
struct _ogonHandler
{
  GObject parent;
};
typedef struct _ogonHandler ogonHandler;

struct _ogonHandlerClass
{
  GObjectClass parent;

  gboolean (*establish_context) (ogonIf *iface, return_ec ** _return, const DWORD_RPC dwScope, GError **error);
  gboolean (*list_readers) (ogonIf *iface, return_lr ** _return, const SCARDCONTEXT_RPC hContext, GError **error);
};
typedef struct _ogonHandlerClass ogonHandlerClass;

GType ogon_handler_get_type (void);
#define TYPE_OGON_HANDLER (ogon_handler_get_type())
#define OGON_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_HANDLER, ogonHandler))
#define IS_OGON_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_HANDLER))
#define OGON_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_OGON_HANDLER, ogonHandlerClass))
#define IS_OGON_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_HANDLER))
#define OGON_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_HANDLER, ogonHandlerClass))

gboolean ogon_handler_establish_context (ogonIf *iface, return_ec ** _return, const DWORD_RPC dwScope, GError **error);
gboolean ogon_handler_list_readers (ogonIf *iface, return_lr ** _return, const SCARDCONTEXT_RPC hContext, GError **error);

/* ogon processor */
struct _ogonProcessor
{
  ThriftDispatchProcessor parent;

  /* protected */
  ogonHandler *handler;
  GHashTable *process_map;
};
typedef struct _ogonProcessor ogonProcessor;

struct _ogonProcessorClass
{
  ThriftDispatchProcessorClass parent;

  /* protected */
  gboolean (*dispatch_call) (ThriftDispatchProcessor *processor,
                             ThriftProtocol *in,
                             ThriftProtocol *out,
                             gchar *fname,
                             gint32 seqid,
                             GError **error);
};
typedef struct _ogonProcessorClass ogonProcessorClass;

GType ogon_processor_get_type (void);
#define TYPE_OGON_PROCESSOR (ogon_processor_get_type())
#define OGON_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_PROCESSOR, ogonProcessor))
#define IS_OGON_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_PROCESSOR))
#define OGON_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_OGON_PROCESSOR, ogonProcessorClass))
#define IS_OGON_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_PROCESSOR))
#define OGON_PROCESSOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_PROCESSOR, ogonProcessorClass))

#endif /* OGON_H */

#ifdef __cplusplus
};
#endif