/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OGON_TYPES_H
#define OGON_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>


#ifdef __cplusplus
extern "C" {
#endif

/* custom thrift includes */

/* begin types */

typedef gint64 DWORD_RPC;

typedef gint64 SCARDCONTEXT_RPC;

typedef gint64 LONG_RPC;

typedef gint64 LPDWORD_RPC;

typedef gchar * LPSTR_RPC;

typedef gchar * LPCSTR_RPC;

/* struct return_ec */
struct _return_ec
{ 
  ThriftStruct parent; 

  /* public */
  gint64 retValue;
  gboolean __isset_retValue;
  gint64 cardContext;
  gboolean __isset_cardContext;
};
typedef struct _return_ec return_ec;

struct _return_ecClass
{
  ThriftStructClass parent;
};
typedef struct _return_ecClass return_ecClass;

GType return_ec_get_type (void);
#define TYPE_RETURN_EC (return_ec_get_type())
#define RETURN_EC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RETURN_EC, return_ec))
#define RETURN_EC_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RETURN_EC, return_ecClass))
#define IS_RETURN_EC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RETURN_EC))
#define IS_RETURN_EC_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RETURN_EC))
#define RETURN_EC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RETURN_EC, return_ecClass))

/* struct return_lr */
struct _return_lr
{ 
  ThriftStruct parent; 

  /* public */
  gint64 retValue;
  gboolean __isset_retValue;
  gchar * mszReaders;
  gboolean __isset_mszReaders;
  gint64 pcchReaders;
  gboolean __isset_pcchReaders;
};
typedef struct _return_lr return_lr;

struct _return_lrClass
{
  ThriftStructClass parent;
};
typedef struct _return_lrClass return_lrClass;

GType return_lr_get_type (void);
#define TYPE_RETURN_LR (return_lr_get_type())
#define RETURN_LR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RETURN_LR, return_lr))
#define RETURN_LR_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RETURN_LR, return_lrClass))
#define IS_RETURN_LR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RETURN_LR))
#define IS_RETURN_LR_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RETURN_LR))
#define RETURN_LR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RETURN_LR, return_lrClass))

/* constants */

/* struct ogonEstablishContextArgs */
struct _ogonEstablishContextArgs
{ 
  ThriftStruct parent; 

  /* public */
  gint64 dwScope;
  gboolean __isset_dwScope;
};
typedef struct _ogonEstablishContextArgs ogonEstablishContextArgs;

struct _ogonEstablishContextArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ogonEstablishContextArgsClass ogonEstablishContextArgsClass;

GType ogon_establish_context_args_get_type (void);
#define TYPE_OGON_ESTABLISH_CONTEXT_ARGS (ogon_establish_context_args_get_type())
#define OGON_ESTABLISH_CONTEXT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_ESTABLISH_CONTEXT_ARGS, ogonEstablishContextArgs))
#define OGON_ESTABLISH_CONTEXT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_OGON_ESTABLISH_CONTEXT_ARGS, ogonEstablishContextArgsClass))
#define IS_OGON_ESTABLISH_CONTEXT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_ESTABLISH_CONTEXT_ARGS))
#define IS_OGON_ESTABLISH_CONTEXT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_ESTABLISH_CONTEXT_ARGS))
#define OGON_ESTABLISH_CONTEXT_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_ESTABLISH_CONTEXT_ARGS, ogonEstablishContextArgsClass))

/* struct ogonEstablishContextResult */
struct _ogonEstablishContextResult
{ 
  ThriftStruct parent; 

  /* public */
  return_ec * success;
  gboolean __isset_success;
};
typedef struct _ogonEstablishContextResult ogonEstablishContextResult;

struct _ogonEstablishContextResultClass
{
  ThriftStructClass parent;
};
typedef struct _ogonEstablishContextResultClass ogonEstablishContextResultClass;

GType ogon_establish_context_result_get_type (void);
#define TYPE_OGON_ESTABLISH_CONTEXT_RESULT (ogon_establish_context_result_get_type())
#define OGON_ESTABLISH_CONTEXT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_ESTABLISH_CONTEXT_RESULT, ogonEstablishContextResult))
#define OGON_ESTABLISH_CONTEXT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_OGON_ESTABLISH_CONTEXT_RESULT, ogonEstablishContextResultClass))
#define IS_OGON_ESTABLISH_CONTEXT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_ESTABLISH_CONTEXT_RESULT))
#define IS_OGON_ESTABLISH_CONTEXT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_ESTABLISH_CONTEXT_RESULT))
#define OGON_ESTABLISH_CONTEXT_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_ESTABLISH_CONTEXT_RESULT, ogonEstablishContextResultClass))

/* struct ogonListReadersArgs */
struct _ogonListReadersArgs
{ 
  ThriftStruct parent; 

  /* public */
  gint64 hContext;
  gboolean __isset_hContext;
};
typedef struct _ogonListReadersArgs ogonListReadersArgs;

struct _ogonListReadersArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ogonListReadersArgsClass ogonListReadersArgsClass;

GType ogon_list_readers_args_get_type (void);
#define TYPE_OGON_LIST_READERS_ARGS (ogon_list_readers_args_get_type())
#define OGON_LIST_READERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_LIST_READERS_ARGS, ogonListReadersArgs))
#define OGON_LIST_READERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_OGON_LIST_READERS_ARGS, ogonListReadersArgsClass))
#define IS_OGON_LIST_READERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_LIST_READERS_ARGS))
#define IS_OGON_LIST_READERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_LIST_READERS_ARGS))
#define OGON_LIST_READERS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_LIST_READERS_ARGS, ogonListReadersArgsClass))

/* struct ogonListReadersResult */
struct _ogonListReadersResult
{ 
  ThriftStruct parent; 

  /* public */
  return_lr * success;
  gboolean __isset_success;
};
typedef struct _ogonListReadersResult ogonListReadersResult;

struct _ogonListReadersResultClass
{
  ThriftStructClass parent;
};
typedef struct _ogonListReadersResultClass ogonListReadersResultClass;

GType ogon_list_readers_result_get_type (void);
#define TYPE_OGON_LIST_READERS_RESULT (ogon_list_readers_result_get_type())
#define OGON_LIST_READERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OGON_LIST_READERS_RESULT, ogonListReadersResult))
#define OGON_LIST_READERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_OGON_LIST_READERS_RESULT, ogonListReadersResultClass))
#define IS_OGON_LIST_READERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OGON_LIST_READERS_RESULT))
#define IS_OGON_LIST_READERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_OGON_LIST_READERS_RESULT))
#define OGON_LIST_READERS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OGON_LIST_READERS_RESULT, ogonListReadersResultClass))

#endif /* OGON_TYPES_H */


#ifdef __cplusplus
};
#endif