/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "ogon_types.h"
#include <thrift/c_glib/thrift.h>

enum _return_ecProperties
{
  PROP_RETURN_EC_0,
  PROP_RETURN_EC_RET_VALUE,
  PROP_RETURN_EC_CARD_CONTEXT
};

/* reads a return_ec object */
static gint32
return_ec_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  return_ec * this_object = RETURN_EC(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->retValue, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_retValue = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->cardContext, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_cardContext = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
return_ec_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  return_ec * this_object = RETURN_EC(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "return_ec", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "retValue", T_I64, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->retValue, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "cardContext", T_I64, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->cardContext, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
return_ec_set_property (GObject *object,
                        guint property_id,
                        const GValue *value,
                        GParamSpec *pspec)
{
  return_ec *self = RETURN_EC (object);

  switch (property_id)
  {
    case PROP_RETURN_EC_RET_VALUE:
      self->retValue = g_value_get_int64 (value);
      self->__isset_retValue = TRUE;
      break;

    case PROP_RETURN_EC_CARD_CONTEXT:
      self->cardContext = g_value_get_int64 (value);
      self->__isset_cardContext = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
return_ec_get_property (GObject *object,
                        guint property_id,
                        GValue *value,
                        GParamSpec *pspec)
{
  return_ec *self = RETURN_EC (object);

  switch (property_id)
  {
    case PROP_RETURN_EC_RET_VALUE:
      g_value_set_int64 (value, self->retValue);
      break;

    case PROP_RETURN_EC_CARD_CONTEXT:
      g_value_set_int64 (value, self->cardContext);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
return_ec_instance_init (return_ec * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->retValue = 0;
  object->__isset_retValue = FALSE;
  object->cardContext = 0;
  object->__isset_cardContext = FALSE;
}

static void 
return_ec_finalize (GObject *object)
{
  return_ec *tobject = RETURN_EC (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
return_ec_class_init (return_ecClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = return_ec_read;
  struct_class->write = return_ec_write;

  gobject_class->finalize = return_ec_finalize;
  gobject_class->get_property = return_ec_get_property;
  gobject_class->set_property = return_ec_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_RETURN_EC_RET_VALUE,
     g_param_spec_int64 ("retValue",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_RETURN_EC_CARD_CONTEXT,
     g_param_spec_int64 ("cardContext",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));
}

GType
return_ec_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (return_ecClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) return_ec_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (return_ec),
      0, /* n_preallocs */
      (GInstanceInitFunc) return_ec_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "return_ecType",
                                   &type_info, 0);
  }

  return type;
}

enum _return_lrProperties
{
  PROP_RETURN_LR_0,
  PROP_RETURN_LR_RET_VALUE,
  PROP_RETURN_LR_MSZ_READERS,
  PROP_RETURN_LR_PCCH_READERS
};

/* reads a return_lr object */
static gint32
return_lr_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  return_lr * this_object = RETURN_LR(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->retValue, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_retValue = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_STRING)
        {
          if (this_object->mszReaders != NULL)
          {
            g_free(this_object->mszReaders);
            this_object->mszReaders = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->mszReaders, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_mszReaders = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->pcchReaders, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_pcchReaders = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
return_lr_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  return_lr * this_object = RETURN_LR(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "return_lr", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "retValue", T_I64, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->retValue, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "mszReaders", T_STRING, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->mszReaders, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "pcchReaders", T_I64, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->pcchReaders, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
return_lr_set_property (GObject *object,
                        guint property_id,
                        const GValue *value,
                        GParamSpec *pspec)
{
  return_lr *self = RETURN_LR (object);

  switch (property_id)
  {
    case PROP_RETURN_LR_RET_VALUE:
      self->retValue = g_value_get_int64 (value);
      self->__isset_retValue = TRUE;
      break;

    case PROP_RETURN_LR_MSZ_READERS:
      if (self->mszReaders != NULL)
        g_free (self->mszReaders);
      self->mszReaders = g_value_dup_string (value);
      self->__isset_mszReaders = TRUE;
      break;

    case PROP_RETURN_LR_PCCH_READERS:
      self->pcchReaders = g_value_get_int64 (value);
      self->__isset_pcchReaders = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
return_lr_get_property (GObject *object,
                        guint property_id,
                        GValue *value,
                        GParamSpec *pspec)
{
  return_lr *self = RETURN_LR (object);

  switch (property_id)
  {
    case PROP_RETURN_LR_RET_VALUE:
      g_value_set_int64 (value, self->retValue);
      break;

    case PROP_RETURN_LR_MSZ_READERS:
      g_value_set_string (value, self->mszReaders);
      break;

    case PROP_RETURN_LR_PCCH_READERS:
      g_value_set_int64 (value, self->pcchReaders);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
return_lr_instance_init (return_lr * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->retValue = 0;
  object->__isset_retValue = FALSE;
  object->mszReaders = NULL;
  object->__isset_mszReaders = FALSE;
  object->pcchReaders = 0;
  object->__isset_pcchReaders = FALSE;
}

static void 
return_lr_finalize (GObject *object)
{
  return_lr *tobject = RETURN_LR (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->mszReaders != NULL)
  {
    g_free(tobject->mszReaders);
    tobject->mszReaders = NULL;
  }
}

static void
return_lr_class_init (return_lrClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = return_lr_read;
  struct_class->write = return_lr_write;

  gobject_class->finalize = return_lr_finalize;
  gobject_class->get_property = return_lr_get_property;
  gobject_class->set_property = return_lr_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_RETURN_LR_RET_VALUE,
     g_param_spec_int64 ("retValue",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_RETURN_LR_MSZ_READERS,
     g_param_spec_string ("mszReaders",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_RETURN_LR_PCCH_READERS,
     g_param_spec_int64 ("pcchReaders",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));
}

GType
return_lr_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (return_lrClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) return_lr_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (return_lr),
      0, /* n_preallocs */
      (GInstanceInitFunc) return_lr_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "return_lrType",
                                   &type_info, 0);
  }

  return type;
}

/* constants */

enum _ogonEstablishContextArgsProperties
{
  PROP_OGON_ESTABLISH_CONTEXT_ARGS_0,
  PROP_OGON_ESTABLISH_CONTEXT_ARGS_DW_SCOPE
};

/* reads a ogon_establish_context_args object */
static gint32
ogon_establish_context_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ogonEstablishContextArgs * this_object = OGON_ESTABLISH_CONTEXT_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->dwScope, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_dwScope = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
ogon_establish_context_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ogonEstablishContextArgs * this_object = OGON_ESTABLISH_CONTEXT_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ogonEstablishContextArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "dwScope", T_I64, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->dwScope, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
ogon_establish_context_args_set_property (GObject *object,
                                          guint property_id,
                                          const GValue *value,
                                          GParamSpec *pspec)
{
  ogonEstablishContextArgs *self = OGON_ESTABLISH_CONTEXT_ARGS (object);

  switch (property_id)
  {
    case PROP_OGON_ESTABLISH_CONTEXT_ARGS_DW_SCOPE:
      self->dwScope = g_value_get_int64 (value);
      self->__isset_dwScope = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ogon_establish_context_args_get_property (GObject *object,
                                          guint property_id,
                                          GValue *value,
                                          GParamSpec *pspec)
{
  ogonEstablishContextArgs *self = OGON_ESTABLISH_CONTEXT_ARGS (object);

  switch (property_id)
  {
    case PROP_OGON_ESTABLISH_CONTEXT_ARGS_DW_SCOPE:
      g_value_set_int64 (value, self->dwScope);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
ogon_establish_context_args_instance_init (ogonEstablishContextArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->dwScope = 0;
  object->__isset_dwScope = FALSE;
}

static void 
ogon_establish_context_args_finalize (GObject *object)
{
  ogonEstablishContextArgs *tobject = OGON_ESTABLISH_CONTEXT_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
ogon_establish_context_args_class_init (ogonEstablishContextArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = ogon_establish_context_args_read;
  struct_class->write = ogon_establish_context_args_write;

  gobject_class->finalize = ogon_establish_context_args_finalize;
  gobject_class->get_property = ogon_establish_context_args_get_property;
  gobject_class->set_property = ogon_establish_context_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_OGON_ESTABLISH_CONTEXT_ARGS_DW_SCOPE,
     g_param_spec_int64 ("dwScope",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));
}

GType
ogon_establish_context_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ogonEstablishContextArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) ogon_establish_context_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ogonEstablishContextArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) ogon_establish_context_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ogonEstablishContextArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _ogonEstablishContextResultProperties
{
  PROP_OGON_ESTABLISH_CONTEXT_RESULT_0,
  PROP_OGON_ESTABLISH_CONTEXT_RESULT_SUCCESS
};

/* reads a ogon_establish_context_result object */
static gint32
ogon_establish_context_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ogonEstablishContextResult * this_object = OGON_ESTABLISH_CONTEXT_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
ogon_establish_context_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ogonEstablishContextResult * this_object = OGON_ESTABLISH_CONTEXT_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ogonEstablishContextResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRUCT, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
ogon_establish_context_result_set_property (GObject *object,
                                            guint property_id,
                                            const GValue *value,
                                            GParamSpec *pspec)
{
  ogonEstablishContextResult *self = OGON_ESTABLISH_CONTEXT_RESULT (object);

  switch (property_id)
  {
    case PROP_OGON_ESTABLISH_CONTEXT_RESULT_SUCCESS:
      if (self->success != NULL)
        g_object_unref (self->success);
      self->success = g_value_dup_object (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ogon_establish_context_result_get_property (GObject *object,
                                            guint property_id,
                                            GValue *value,
                                            GParamSpec *pspec)
{
  ogonEstablishContextResult *self = OGON_ESTABLISH_CONTEXT_RESULT (object);

  switch (property_id)
  {
    case PROP_OGON_ESTABLISH_CONTEXT_RESULT_SUCCESS:
      g_value_set_object (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
ogon_establish_context_result_instance_init (ogonEstablishContextResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = g_object_new (TYPE_RETURN_EC, NULL);
  object->__isset_success = FALSE;
}

static void 
ogon_establish_context_result_finalize (GObject *object)
{
  ogonEstablishContextResult *tobject = OGON_ESTABLISH_CONTEXT_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_object_unref(tobject->success);
    tobject->success = NULL;
  }
}

static void
ogon_establish_context_result_class_init (ogonEstablishContextResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = ogon_establish_context_result_read;
  struct_class->write = ogon_establish_context_result_write;

  gobject_class->finalize = ogon_establish_context_result_finalize;
  gobject_class->get_property = ogon_establish_context_result_get_property;
  gobject_class->set_property = ogon_establish_context_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_OGON_ESTABLISH_CONTEXT_RESULT_SUCCESS,
     g_param_spec_object ("success",
                         NULL,
                         NULL,
                         TYPE_RETURN_EC,
                         G_PARAM_READWRITE));
}

GType
ogon_establish_context_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ogonEstablishContextResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) ogon_establish_context_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ogonEstablishContextResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) ogon_establish_context_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ogonEstablishContextResultType",
                                   &type_info, 0);
  }

  return type;
}

enum _ogonListReadersArgsProperties
{
  PROP_OGON_LIST_READERS_ARGS_0,
  PROP_OGON_LIST_READERS_ARGS_H_CONTEXT
};

/* reads a ogon_list_readers_args object */
static gint32
ogon_list_readers_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ogonListReadersArgs * this_object = OGON_LIST_READERS_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->hContext, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_hContext = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
ogon_list_readers_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ogonListReadersArgs * this_object = OGON_LIST_READERS_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ogonListReadersArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "hContext", T_I64, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->hContext, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
ogon_list_readers_args_set_property (GObject *object,
                                     guint property_id,
                                     const GValue *value,
                                     GParamSpec *pspec)
{
  ogonListReadersArgs *self = OGON_LIST_READERS_ARGS (object);

  switch (property_id)
  {
    case PROP_OGON_LIST_READERS_ARGS_H_CONTEXT:
      self->hContext = g_value_get_int64 (value);
      self->__isset_hContext = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ogon_list_readers_args_get_property (GObject *object,
                                     guint property_id,
                                     GValue *value,
                                     GParamSpec *pspec)
{
  ogonListReadersArgs *self = OGON_LIST_READERS_ARGS (object);

  switch (property_id)
  {
    case PROP_OGON_LIST_READERS_ARGS_H_CONTEXT:
      g_value_set_int64 (value, self->hContext);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
ogon_list_readers_args_instance_init (ogonListReadersArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->hContext = 0;
  object->__isset_hContext = FALSE;
}

static void 
ogon_list_readers_args_finalize (GObject *object)
{
  ogonListReadersArgs *tobject = OGON_LIST_READERS_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
ogon_list_readers_args_class_init (ogonListReadersArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = ogon_list_readers_args_read;
  struct_class->write = ogon_list_readers_args_write;

  gobject_class->finalize = ogon_list_readers_args_finalize;
  gobject_class->get_property = ogon_list_readers_args_get_property;
  gobject_class->set_property = ogon_list_readers_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_OGON_LIST_READERS_ARGS_H_CONTEXT,
     g_param_spec_int64 ("hContext",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));
}

GType
ogon_list_readers_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ogonListReadersArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) ogon_list_readers_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ogonListReadersArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) ogon_list_readers_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ogonListReadersArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _ogonListReadersResultProperties
{
  PROP_OGON_LIST_READERS_RESULT_0,
  PROP_OGON_LIST_READERS_RESULT_SUCCESS
};

/* reads a ogon_list_readers_result object */
static gint32
ogon_list_readers_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ogonListReadersResult * this_object = OGON_LIST_READERS_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
ogon_list_readers_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ogonListReadersResult * this_object = OGON_LIST_READERS_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ogonListReadersResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRUCT, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
ogon_list_readers_result_set_property (GObject *object,
                                       guint property_id,
                                       const GValue *value,
                                       GParamSpec *pspec)
{
  ogonListReadersResult *self = OGON_LIST_READERS_RESULT (object);

  switch (property_id)
  {
    case PROP_OGON_LIST_READERS_RESULT_SUCCESS:
      if (self->success != NULL)
        g_object_unref (self->success);
      self->success = g_value_dup_object (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
ogon_list_readers_result_get_property (GObject *object,
                                       guint property_id,
                                       GValue *value,
                                       GParamSpec *pspec)
{
  ogonListReadersResult *self = OGON_LIST_READERS_RESULT (object);

  switch (property_id)
  {
    case PROP_OGON_LIST_READERS_RESULT_SUCCESS:
      g_value_set_object (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
ogon_list_readers_result_instance_init (ogonListReadersResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = g_object_new (TYPE_RETURN_LR, NULL);
  object->__isset_success = FALSE;
}

static void 
ogon_list_readers_result_finalize (GObject *object)
{
  ogonListReadersResult *tobject = OGON_LIST_READERS_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_object_unref(tobject->success);
    tobject->success = NULL;
  }
}

static void
ogon_list_readers_result_class_init (ogonListReadersResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = ogon_list_readers_result_read;
  struct_class->write = ogon_list_readers_result_write;

  gobject_class->finalize = ogon_list_readers_result_finalize;
  gobject_class->get_property = ogon_list_readers_result_get_property;
  gobject_class->set_property = ogon_list_readers_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_OGON_LIST_READERS_RESULT_SUCCESS,
     g_param_spec_object ("success",
                         NULL,
                         NULL,
                         TYPE_RETURN_LR,
                         G_PARAM_READWRITE));
}

GType
ogon_list_readers_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ogonListReadersResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) ogon_list_readers_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ogonListReadersResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) ogon_list_readers_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ogonListReadersResultType",
                                   &type_info, 0);
  }

  return type;
}

